---

- name: CCS submission tasks
  tags: 
    - "@example-ccs"  # All events defined in example-ccs track
    - "#task"  # All events with "task" tag
  start: Apr 3
  end: Jul 3
  filename: ccs-tasks

- name: 2023 Spring
  tags: []
  start: 2023/03/29
  end: 2023/06/16
  filename: 23spring.png